# Generated by Django 6.1.1 on 2026-09-27 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Комментарий')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_note', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Внутренний комментарий',
                'verbose_name_plural': 'Внутренние комментарии',
            },
        ),
    ]
