# Generated by Django 6.1.1 on 2026-09-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание'),
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало'),
        ),
    ]
