# Generated by Django 6.1.1 on 2026-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_actual_end_booking_actual_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_hours', models.PositiveIntegerField(default=24, verbose_name='Отмена и перенос не позднее чем за, ч')),
            ],
            options={
                'verbose_name': 'Правило отмены',
                'verbose_name_plural': 'Правило отмены',
            },
        ),
    ]
