# Generated by Django 6.1.1 on 2026-09-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('cosmetics', 'Косметика'), ('consumables', 'Расходные материалы')], max_length=20, verbose_name='Категория')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('unit', models.CharField(default='шт', max_length=10, verbose_name='Ед. изм.')),
                ('min_quantity', models.PositiveIntegerField(default=0, verbose_name='Минимальный остаток')),
            ],
            options={
                'verbose_name': 'Позиция на складе',
                'verbose_name_plural': 'Склад',
                'ordering': ['category', 'name'],
            },
        ),
    ]
